<?php
	$TGL=$_POST["TGL"];
	$GROSS_PROD=$_POST["GROSS_PROD"];
	$NETT_PROD=$_POST["NETT_PROD"];
	$ALLOCATED_PROD=$_POST["ALLOCATED_PROD"];
	$EKSPOR_SPRL_DAILY=$_POST["EKSPOR_SPRL_DAILY"];
	$EKSPOR_SPRL_CUM=$_POST["EKSPOR_SPRL_CUM"];
	$DOMESTIK_GOI_TANKER_DAILY=$_POST["DOMESTIK_GOI_TANKER_DAILY"];
	$DOMESTIK_GOI_TANKER_CUM=$_POST["DOMESTIK_GOI_TANKER_CUM"];
	$DOMESTIK_GOI_PIPA_DAILY=$_POST["DOMESTIK_GOI_PIPA_DAILY"];
	$DOMESTIK_GOI_PIPA_CUM=$_POST["DOMESTIK_GOI_PIPA_CUM"];
	$OPENING_TERMINAL=$_POST["OPENING_TERMINAL"];
	$OPENING_FIELD=$_POST["OPENING_FIELD"];
	$OWN_USE=$_POST["OWN_USE"];
	$ENDING_TERMINAL=$_POST["ENDING_TERMINAL"];
	$ENDING_DEAD_TERMINAL=$_POST["ENDING_DEAD_TERMINAL"];
	$ENDING_FIELD=$_POST["ENDING_FIELD"];
	$ENDING_DEAD_FIELD=$_POST["ENDING_DEAD_FIELD"];
	$DUMAI_LOSS_GAIN=$_POST["DUMAI_LOSS_GAIN"];
	
	//BUAT DEBUG
	/*echo(
		$TGL . "<br>" .
		$GROSS_PROD . "<br>" .
		$NETT_PROD . "<br>" .
		$ALLOCATED_PROD . "<br>" .
		$EKSPOR_SPRL_DAILY . "<br>" .
		$EKSPOR_SPRL_CUM . "<br>" .
		$DOMESTIK_GOI_TANKER_DAILY . "<br>" .
		$DOMESTIK_GOI_TANKER_CUM . "<br>" .
		$DOMESTIK_GOI_PIPA_DAILY . "<br>" .
		$DOMESTIK_GOI_PIPA_CUM . "<br>" .
		$OPENING_TERMINAL . "<br>" .
		$OPENING_FIELD . "<br>" .
		$OWN_USE . "<br>" .
		$ENDING_TERMINAL . "<br>" .
		$ENDING_DEAD_TERMINAL . "<br>" .
		$ENDING_FIELD . "<br>" .
		$ENDING_DEAD_FIELD . "<br>" .
		$DUMAI_LOSS_GAIN
	);
	*/
	
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "webdev";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 

$sql = "INSERT INTO sot_sprl (TGL, GROSS_PROD, NETT_PROD, ALLOCATED_PROD, EKSPOR_SPRL_DAILY, EKSPOR_SPRL_CUM , DOMESTIK_GOI_TANKER_DAILY, 	DOMESTIK_GOI_TANKER_CUM, DOMESTIK_GOI_PIPA_DAILY, DOMESTIK_GOI_PIPA_CUM, OPENING_TERMINAL, OPENING_FIELD, OWN_USE, ENDING_TERMINAL, ENDING_DEAD_TERMINAL, ENDING_FIELD, ENDING_DEAD_FIELD, DUMAI_LOSS_GAIN)
VALUES ('$TGL', '$GROSS_PROD', '$NETT_PROD', '$ALLOCATED_PROD', '$EKSPOR_SPRL_DAILY', '$EKSPOR_SPRL_CUM' , '$DOMESTIK_GOI_TANKER_DAILY', '$DOMESTIK_GOI_TANKER_CUM', '$DOMESTIK_GOI_PIPA_DAILY', '$DOMESTIK_GOI_PIPA_CUM', '$OPENING_TERMINAL', '$OPENING_FIELD', '$OWN_USE', '$ENDING_TERMINAL', '$ENDING_DEAD_TERMINAL', '$ENDING_FIELD', '$ENDING_DEAD_FIELD', '$DUMAI_LOSS_GAIN')";

if ($conn->query($sql) === TRUE) {
			echo "<script> alert('Saving Data Success');
			location='sotsprl.php';
			</script>";
} else {
    echo "Saving Data Failed" . $sql . "<br>" . $conn->error;
}

$conn->close();
?>
